name: Build and Deploy Flutter Web App

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build web app
      run: flutter build web --release --base-href https://jemisgoti.github.io/flutter-login-pages/
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_branch: gh-pages  # default: gh-pages
        publish_dir: ./build/web
        force_orphan: true
